<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ProductModel;

class ProductModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        ProductModel::create([
            'cate_id' => '4',
            'name' => 'Snapper',
            'small_description' => 'Snapper',
            'description' => 'Red Snapper',
            'original_price' => '1100',
            'selling_price' => '1200',
            'image' => 'https://www.thefishsociety.co.uk/media/image/b3/95/c3/snapper-whole-min.jpg',
            'qty' => '100',
            'tax' => '100',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Dairy',
            'meta_description'=> 'Dairy Food grown in jamaica',
            'meta_keyword'=> 'Dairy Food Group',

        ]);
        ProductModel::create([
            'cate_id' => '4',
            'name' => 'Doctor',
            'small_description' => 'Snapper',
            'description' => 'Red Snapper',
            'original_price' => '600',
            'selling_price' => '750',
            'image' => 'https://s2r.iucnredlist.org/sis2_images/1764135573.jpg',
            'qty' => '100',
            'tax' => '100',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Dairy',
            'meta_description'=> 'Dairy Food grown in jamaica',
            'meta_keyword'=> 'Dairy Food Group',
        ]);
        ProductModel::create([
            'cate_id' => '4',
            'name' => 'Welchman',
            'small_description' => 'Snapper',
            'description' => 'Red Snapper',
            'original_price' => '600',
            'selling_price' => '750',
            'image' => 'https://fishesofaustralia.net.au/images/image/SargocentTiereiod2JTW.jpg',
            'qty' => '100',
            'tax' => '100',
            'status' => '0',
            'trending' => '0',
            'meta_title'=> 'Dairy',
            'meta_description'=> 'Dairy Food grown in jamaica',
            'meta_keyword'=> 'Dairy Food Group',
        ]);
        ProductModel::create([
            'cate_id' => '4',
            'name' => 'Land Crab',
            'small_description' => 'Snapper',
            'description' => 'Red Snapper',
            'original_price' => '600',
            'selling_price' => '750',
            'description' => 'Clean and chop up',
            'image' => 'https://d2j6dbq0eux0bg.cloudfront.net/images/31162554/1478089605.jpg',
            'qty' => '100',
            'tax' => '100',
            'status' => '1',
            'trending' => '0',
            'meta_title'=> 'Dairy',
            'meta_description'=> 'Dairy Food grown in jamaica',
            'meta_keyword'=> 'Dairy Food Group',
        ]);
        ProductModel::create([
            'cate_id' => '4',
            'name' => 'Lobster',
            'small_description' => 'Snapper',
            'description' => 'Red Snapper',
            'original_price' => '600',
            'selling_price' => '750',
            'image' => 'https://mediad.publicbroadcasting.net/p/waer/files/styles/x_large/public/201711/lobster.jpg',
            'qty' => '100',
            'tax' => '100',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Dairy',
            'meta_description'=> 'Dairy Food grown in jamaica',
            'meta_keyword'=> 'Dairy Food Group',
        ]);
        ProductModel::create([
            'cate_id' => '4',
            'name' => 'Shrimp',
            'small_description' => 'Snapper',
            'description' => 'Red Snapper',
            'original_price' => '600',
            'selling_price' => '750',
            'image' => 'https://classicdeli.co.uk/762-full_default/frozen-red-carabineros-prawn-15-20pcs-1kg.jpg',
            'qty' => '100',
            'tax' => '100',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Dairy',
            'meta_description'=> 'Dairy Food grown in jamaica',
            'meta_keyword'=> 'Dairy Food Group',
        ]);
        ProductModel::create([
            'cate_id' => '1',
            'name' => 'Apple',
            'small_description' => 'Apple',
            'description' => 'Red Snapper',
            'original_price' => '1000',
            'selling_price' => '1200',
            'image' => 'https://healthjade.com/wp-content/uploads/2017/10/apple-fruit.jpg',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Fruits',
            'meta_description'=> 'Dairy Food grown in jamaica',
            'meta_keyword'=> 'Apple',

        ]);
        ProductModel::create([
            'cate_id' => '1',
            'name' => 'Banana',
            'small_description' => 'Banana',
            'description' => 'Banana',
            'original_price' => '800',
            'selling_price' => '750',
            'image' => 'https://5.imimg.com/data5/VY/QT/MY-51857835/banana-fruit-500x500.jpg',
            'qty' => '100',
            'tax' => '1',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Fruits',
            'meta_description'=> 'Dairy Food grown in jamaica',
            'meta_keyword'=> 'Banan',
        ]);
        ProductModel::create([
            'cate_id' => '1',
            'name' => 'Grape',
            'small_description' => 'Grape',
            'description' => 'Grape',
            'original_price' => '800',
            'selling_price' => '750',
            'image' => 'https://th.bing.com/th/id/OIP.dNMCJee9TMXIqIINgjuGuAHaF7?pid=ImgDet&rs=1',
            'qty' => '100',
            'tax' => '10',
            'status' => '0',
            'trending' => '0',
            'meta_title'=> 'Fruits',
            'meta_description'=> 'Grape Food grown in jamaica',
            'meta_keyword'=> 'Grape',
        ]);
        ProductModel::create([
            'cate_id' => '1',
            'name' => 'Orange',
            'small_description' => 'Orange',
            'description' => 'Orange',
            'original_price' => '800',
            'selling_price' => '750',
            'description' => 'Clean and chop up',
            'image' => 'https://thepartysource.com/image/cache/catalog/inventory/ORANGE-500x500.jpg',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '0',
            'meta_title'=> 'Fruits',
            'meta_description'=> 'Dairy Food grown in jamaica',
            'meta_keyword'=> 'Orange',
        ]);
        ProductModel::create([
            'cate_id' => '1',
            'name' => 'Pinapple',
            'small_description' => 'Painapple',
            'description' => 'Painapple',
            'original_price' => '800',
            'selling_price' => '750',
            'image' => 'https://www.linwoodtrust.org.uk/products/131-large.jpg',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Fruits',
            'meta_description'=> 'Form Food grown in jamaica by jamaicans',
            'meta_keyword'=> 'Painapple',
        ]);
        ProductModel::create([
            'cate_id' => '1',
            'name' => 'Mango',
            'small_description' => 'Mango',
            'description' => 'Mango',
            'original_price' => '800',
            'selling_price' => '750',
            'image' => 'https://th.bing.com/th/id/OIP.P3cBY1JTvodNRNubixhOaQHaFj?pid=ImgDet&rs=1',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Fruits',
            'meta_description'=> 'Form Food grown in jamaica by jamaicans',
            'meta_keyword'=> 'Mango',
        ]);
        ProductModel::create([
            'cate_id' => '3',
            'name' => 'Goat',
            'small_description' => 'Goat',
            'description' => 'Goat',
            'original_price' => '1300',
            'selling_price' => '1200',
            'image' => 'https://th.bing.com/th/id/OIP.iGkvaIJC3IBXLkHxu7r5UwHaE8?pid=ImgDet&rs=1',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Meat',
            'meta_description'=> 'Meats grown in jamaica by our local farmers',
            'meta_keyword'=> 'Goat',

        ]);
        ProductModel::create([
            'cate_id' => '3',
            'name' => 'Chicken',
            'small_description' => 'Chicken',
            'description' => 'Chicken grown in the comfort of there own space',
            'original_price' => '700',
            'selling_price' => '600',
            'image' => 'https://th.bing.com/th/id/OIP.CAwePwvLIZil6l4FvT531wHaE7?pid=ImgDet&rs=1',
            'qty' => '100',
            'tax' => '1',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Meat',
            'meta_description'=> 'Meats grown in jamaica by our local farmers',
            'meta_keyword'=> 'Chicken',
        ]);
        ProductModel::create([
            'cate_id' => '3',
            'name' => 'Pork Chop',
            'small_description' => 'Pork Chop grown in the comfort of there own space',
            'description' => 'Pork Chop grown in the comfort of there own space',
            'original_price' => '700',
            'selling_price' => '600',
            'image' => 'https://th.bing.com/th/id/OIP.Z0M5tB96kGwtHQYdvFLgHAHaEu?pid=ImgDet&w=862&h=550&rs=1',
            'qty' => '100',
            'tax' => '10',
            'status' => '0',
            'trending' => '0',
            'meta_title'=> 'Meats',
            'meta_description'=> 'Meats grown in jamaica by our local farmers',
            'meta_keyword'=> 'Pork Chop',
        ]);
        ProductModel::create([
            'cate_id' => '2',
            'name' => 'Tomato',
            'small_description' => 'Tomato grown in jamaica by our very own formers',
            'description' => 'Tomato grown in jamaica by our very own formers',
            'original_price' => '700',
            'selling_price' => '600',
            'description' => 'Clean and chop up',
            'image' => 'https://th.bing.com/th/id/R.4e1a69a05c645d70f0714ff4b2060eb1?rik=0lZVLU4PcoNW6A&pid=ImgRaw&r=0',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '0',
            'meta_title'=> 'Vagitable',
            'meta_description'=> 'Form Food grown in jamaica by jamaicans',
            'meta_keyword'=> 'Tomato',
        ]);
        ProductModel::create([
            'cate_id' => '2',
            'name' => 'Sweet Paper',
            'small_description' => 'Sweet paper grown in jamaica by our very own formers',
            'description' => 'Sweet paper grown in jamaica by our very own formers',
            'original_price' => '700',
            'selling_price' => '600',
            'image' => 'https://4.imimg.com/data4/NS/NN/MY-17028966/capcicum-250x250.jpg',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Vagitable',
            'meta_description'=> 'Form Food grown in jamaica by jamaicans',
            'meta_keyword'=> 'Sweet Paper',
        ]);
        ProductModel::create([
            'cate_id' => '2',
            'name' => 'Onians',
            'small_description' => 'Onians grown in jamaica by our very own formers',
            'description' => 'Onians grown in jamaica by our very own formers',
            'original_price' => '700',
            'selling_price' => '600',
            'image' => 'https://vicconexports.com/wp-content/uploads/2020/09/AdobeStock_52790580-scaled-1024x900.jpeg',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Vagitable',
            'meta_description'=> 'Form Food grown in jamaica by jamaicans',
            'meta_keyword'=> 'Onians',
        ]);
        ProductModel::create([
            'cate_id' => '5',
            'name' => 'Milk',
            'small_description' => 'Tomato grown in jamaica by our very own formers',
            'description' => 'Milk milk from our very own cows in jamaica',
            'original_price' => '700',
            'selling_price' => '600',
            'description' => 'Clean and chop up',
            'image' => 'https://i.pinimg.com/originals/03/68/44/03684499fd3dfaf6579fa3049ef965b2.png',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '0',
            'meta_title'=> 'Dairy',
            'meta_description'=> 'Form Food grown in jamaica by jamaicans',
            'meta_keyword'=> 'Milk',
        ]);
        ProductModel::create([
            'cate_id' => '5',
            'name' => 'Egg',
            'small_description' => 'Eggs grown in jamaica by our very own folws',
            'description' => 'Eggs grown in jamaica by our very own folws',
            'original_price' => '700',
            'selling_price' => '600',
            'image' => 'https://pbs.twimg.com/profile_images/1115599702/farmfresheggs_400x400.jpg',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Dairy',
            'meta_description'=> 'Form Food produce in jamaica by jamaicans',
            'meta_keyword'=> 'Egg',
        ]);
        ProductModel::create([
            'cate_id' => '5',
            'name' => 'Cheese',
            'small_description' => 'Cheese produce in jamaica by our very own formers',
            'description' => 'Cheese produce in jamaica by our very own formers',
            'original_price' => '700',
            'selling_price' => '600',
            'image' => 'https://spin.atomicobject.com/wp-content/uploads/20190209150441/Cheese.jpg',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Dairy',
            'meta_description'=> 'Form Food produce in jamaica by jamaicans',
            'meta_keyword'=> 'Dairy',
        ]);
        ProductModel::create([
            'cate_id' => '6',
            'name' => 'Coconut Oil',
            'small_description' => 'Coconut Oile produce from our very own local cocnut in jamaica by our very own formers',
            'description' => 'Coconut Oile produce from our very own local cocnut in jamaica by our very own formers',
            'original_price' => '700',
            'selling_price' => '600',
            'description' => 'Clean and chop up',
            'image' => 'https://i.pinimg.com/originals/fe/22/cf/fe22cfab7176de73d9269bb9d6d21a73.jpg',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '0',
            'meta_title'=> 'Oil',
            'meta_description'=> 'Form Food grown in jamaica by jamaicans',
            'meta_keyword'=> 'Coconut Oil',
        ]);
        ProductModel::create([
            'cate_id' => '6',
            'name' => 'Olive Oil',
            'small_description' => 'Olive Oil produce from our very own local cocnut in jamaica by our very own formers',
            'description' => 'Olive Oil produce from our very own local cocnut in jamaica by our very own formers',
            'original_price' => '700',
            'selling_price' => '600',
            'image' => 'https://post.medicalnewstoday.com/wp-content/uploads/sites/3/2020/02/323007_1100-800x825.jpg',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'Oil',
            'meta_description'=> 'Form Food produce in jamaica by jamaicans',
            'meta_keyword'=> 'Olive Oil',
        ]);
        ProductModel::create([
            'cate_id' => '6',
            'name' => 'Sun Flower Oil',
            'small_description' => 'Sun Flower Oil produce from our very own local cocnut in jamaica by our very own formers',
            'description' => 'Sun Flower Oil produce from our very own local cocnut in jamaica by our very own formers',
            'original_price' => '700',
            'selling_price' => '600',
            'image' => 'https://cpimg.tistatic.com/06053573/b/4/Refined-Sunflower-Oil.jpg',
            'qty' => '100',
            'tax' => '10',
            'status' => '1',
            'trending' => '1',
            'meta_title'=> 'oil',
            'meta_description'=> 'Form Food produce in jamaica by jamaicans',
            'meta_keyword'=> 'Sun Flower Oil',
        ]);
    }
}
